metadata:
  name: self_healing_terraform_agent
  version: "1.0.0"
  author: "Your Name"
  description: "A LangGraph workflow for autonomous, self-healing Terraform execution using Claude."


version: 1
description: >
  Self-Healing Terraform Agent powered by LangGraph.
  This workflow:
    1. Generates Terraform code from user prompt.
    2. Runs Terraform init/plan/apply once.
    3. If failure, uses Claude to repair the code.
    4. Retries until success or max attempts.
    5. Returns final Terraform result + all attempts.

states:
  input:
    type: object
    required: [prompt]
    properties:
      prompt:
        type: string
        description: User's natural-language request for provisioning.

  terraform_code:
    type: object
    properties:
      tf_code:
        type: string

  execution_result:
    type: object
    properties:
      stage:
        type: string
      success:
        type: boolean
      stdout:
        type: string
      stderr:
        type: string
      tf_code:
        type: string

  healed_code:
    type: object
    properties:
      tf_code:
        type: string

  final:
    type: object
    properties:
      success:
        type: boolean
      attempts:
        type: array
        items:
          type: object
      tf_final:
        type: string

nodes:
  generate_tf:
    type: llm
    model: claude-3-5-sonnet
    input: |
      You are an AWS Terraform expert.
      Convert the user request below into VALID Terraform HCL.

      NO explanations.
      NO markdown.
      NO backticks.
      Return ONLY the Terraform configuration.

      User request:
      {{input.prompt}}
    output: |
      { "tf_code": "{{response}}" }

  run_tf:
    type: python
    path: services/terraform_exec.py
    function: run_terraform_once
    input_mapping:
      tf_code: terraform_code.tf_code
    output_mapping:
      stage: stage
      success: success
      stdout: stdout
      stderr: stderr
      tf_code: tf_code

  heal_tf:
    type: python
    path: services/terraform_exec.py
    function: heal_terraform
    input_mapping:
      tf_code: execution_result.tf_code
      stage: execution_result.stage
      stderr: execution_result.stderr
      stdout: execution_result.stdout
    output_mapping:
      tf_code: tf_code

edges:
  - from: input
    to: generate_tf
    map_result_to: terraform_code

  - from: generate_tf
    to: run_tf
    map_result_to: execution_result

  - condition: "{{execution_result.success == false}}"
    from: run_tf
    to: heal_tf
    map_result_to: healed_code

  - condition: "{{execution_result.success == false}}"
    from: heal_tf
    to: run_tf
    map:
      terraform_code.tf_code: healed_code.tf_code

  - condition: "{{execution_result.success == true}}"
    from: run_tf
    to: final
    map_result_to: final

limits:
  max_retries: 3
  stop_after_success: true
